# fish configuration files

:bash: https://www.gnu.org/software/bash/[bash]
:cargo: https://doc.rust-lang.org/cargo/[cargo]
:doas: https://github.com/slicer69/doas/[doas]
:fish: https://fishshell.com/[fish]
:fish-ppa: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3[fish PPA]
:fish-tide-compatibility: https://github.com/IlanCosman/tide/wiki/Fish-version-compatibility[Fish version compatibility]
:fisher: https://github.com/jorgebucaran/fisher[fisher]
:git: https://git-scm.com/[Git]
:lsd: https://github.com/lsd-rs/lsd[lsd]
:nerd-fonts: https://www.nerdfonts.com/[Nerd Fonts]
:opendoas: https://github.com/Duncaen/OpenDoas[OpenDoas]
:pleaser: https://crates.io/crates/pleaser[pleaser]
:sudo: https://www.sudo.ws/[sudo]
:tide: https://github.com/IlanCosman/tide[tide]

## Features

- Install {fish} and link {fish} configuration files (directories `conf.d` and `functions`)
- Install {fisher} and selected plugins (see link:fish_plugins[])
- Install selected {nerd-fonts}
- Replace `ls` with {lsd}

## System requirements

Different distributions and releases ship with different fish versions.

The biggest source of problems is the compatibility between {fish} and {tide}
(see {fish-tide-compatibility})

To guarantee compatibility with the least possible maintenance effort,
the latest {fish} version required, and the {fisher} plugins have been fixed
to the specific versions known to work with the current {fish} version.

Therefore, only the following combinations are supported:

[cols="3*",options="header"]
|===

| OS version
| fish version
| Package source

| Fedora 37
| 3.6.0
| Official Fedora repository

| Ubuntu 22.04
| 3.6.0
| {fish-ppa}

|===

## Installation

. Install the following prerrequisites:
+
 * {bash}
 * {git}
+
If you're not running the script as root, you'll also need one of these:
** {sudo}
** {doas} or {opendoas}
** {pleaser}

. Clone the repository:
* Using HTTPS:
+
[source,bash]
----
git clone https://github.com/jonancm/dotfiles_fish.git
----
* Using SSH:
+
[source,bash]
----
git clone git@github.com:jonancm/dotfiles_fish.git
----

. Run the installation script:
+
[source,bash]
----
bash install.sh
----

[NOTE]
====
Some distributions might require some previous setup steps before you can
run the install script.

Please check the <<testing>> section for distribution-specific prerrequisites.
====

[[testing]]
## Testing

### Prerrequisites

* https://podman.io/[Podman]

[NOTE]
====
When using Podman with SELinux, you must
https://devops.stackexchange.com/a/11277[add `:z` when you mount a volume].

The commands in the following section reflect this.
====

### Fedora 37

. Start the container:
+
[source,bash]
----
podman run -it -v $PWD:/ws:z -w /ws --rm fedora:37
----

. Run the install script:
+
[source,bash]
----
./install.sh
----

### Ubuntu 22.04

. Start the container:
+
[source,bash]
----
podman run -it -v $PWD:/ws:z -w /ws --rm ubuntu:22.04
----

. Add the {fish-ppa} and upgrade to the latest {fish} version:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:fish-shell/release-3
----
+
This is needed to install the latest {fish} version that is compatible with
our selected {tide} version.
+
If you hadn't installed {fish} before, you don't have to do anything else,
since the installation script will already try to install {fish}.
+
If {fish} was already installed, you'll have to upgrade it manually before
running the installation script:
+
[source,bash]
----
sudo apt-get update
sudo apt-get upgrade
----

. Install {lsd}.
Since {lsd} is not available in the Ubuntu repository, you'll have to install
it with {cargo}:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install cargo rustc
cargo install lsd
export PATH="$HOME/.cargo/bin:$PATH"
----

. Run the install script:
+
[source,bash]
----
./install.sh
----
